---
- name: Gather EC2 facts.
  ec2_remote_facts:
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2_facts

- name: Debug ec2 facts
  debug:
    msg: "{{ ec2_facts.instances }}"

- name: Terminate aws instance
  local_action:
        module: ec2
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: 'absent'
        instance_ids: "{{ item.id  }}"
        wait: True
  with_items:
   - "{{ ec2_facts.instances }}"

